export { Profile as ProfileReact1 } from "@/registry/react/profile/profile"
export { Profile as ProfileReact2 } from "@/registry/react/profile/profile-2"
export { Profile as ProfileReact3 } from "@/registry/react/profile/profile-3"
export { Profile as ProfileReact4 } from "@/registry/react/profile/profile-4"
export { Profile as ProfileReact5 } from "@/registry/react/profile/profile-5"
