export { Profile as ProfileNextApp1 } from "@/registry/next/app-router/profile/profile"
export { Profile as ProfileNextApp2 } from "@/registry/next/app-router/profile/profile-2"
export { Profile as ProfileNextApp3 } from "@/registry/next/app-router/profile/profile-3"
export { Profile as ProfileNextApp4 } from "@/registry/next/app-router/profile/profile-4"
export { Profile as ProfileNextApp5 } from "@/registry/next/app-router/profile/profile-5"
