export { Preferences as PreferencesReact1 } from "@/registry/react/preferences/preferences"
export { Preferences as PreferencesReact2 } from "@/registry/react/preferences/preferences-2"
export { Preferences as PreferencesReact3 } from "@/registry/react/preferences/preferences-3"
export { Preferences as PreferencesReact4 } from "@/registry/react/preferences/preferences-4"
export { Preferences as PreferencesReact5 } from "@/registry/react/preferences/preferences-5"
